### ISSUE TITLE
ImportError: cannot import name 'cached_property'

### ISSUE THREAD

**Issue by Wrench-wench** [ArmindoFlores/ao3_api#3]
When running the first snippet of code in the README saved as a .py file to get the WorkID. I get an error message that it cannot import from functools.

The resulting error message occurs regardless of if I run it from the ao3_api or AO3 directory.

Fresh Ubuntu 18.04 LTS in VirtualBox.
```
(project) ao3dude@ao3dude-VirtualBox:~/project$ python3 ~/project/ao3_api/snippet.py 
Traceback (most recent call last):
  File "/home/ao3dude/project/ao3_api/snippet.py", line 1, in <module>
    import AO3
  File "/home/ao3dude/project/ao3_api/AO3/__init__.py", line 2, in <module>
    from .comments import Comment
  File "/home/ao3dude/project/ao3_api/AO3/comments.py", line 5, in <module>
    from .users import User
  File "/home/ao3dude/project/ao3_api/AO3/users.py", line 2, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property'
```
Here are the commands I used to setup the environment: 
```
# Update the OS software and grab some Python packages. 
sudo apt update && sudo apt upgrade -y
sudo apt install python3-dev python3-pip python3-venv git

# Make a directory and start a Python virtual environment in it.
mkdir projectfolder 
python3 -m venv --system-site-packages projectfolder/
source projectfolder/bin/activate

# Move in to the folder, get some needed Python modules and clone the git.
cd projectfolder/
pip install --upgrade pip setuptools
git clone https://github.com/ArmindoFlores/ao3_api.git
```

**Comment by Wrench-wench** [comment]
This is the result when I tried to fix the issue by installing functools with pip

(project) ao3dude@ao3dude-VirtualBox:~/project$ pip install --upgrade functools
Collecting functools
  Downloading functools-0.5.tar.gz (4.9 kB)
Building wheels for collected packages: functools
  Building wheel for functools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ao3dude/project/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-38iys3v6/functools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-38iys3v6/functools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5ziymtjy
       cwd: /tmp/pip-install-38iys3v6/functools/
  Complete output (115 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  copying functools.py -> build/lib.linux-x86_64-3.6
  running build_ext
  building '_functools' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ao3dude/project/include -I/usr/include/python3.6m -c src/functools.c -o build/temp.linux-x86_64-3.6/src/functools.o
  src/functools.c: In function ‘init_functools’:
  src/functools.c:43:6: warning: implicit declaration of function ‘Py_InitModule3’; did you mean ‘Py_Initialize’? [-Wimplicit-function-declaration]
    m = Py_InitModule3("_functools", NULL, functools_doc);
        ^~~~~~~~~~~~~~
        Py_Initialize
  src/functools.c:43:4: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    m = Py_InitModule3("_functools", NULL, functools_doc);
      ^
  src/functools.c:45:3: warning: ‘return’ with no value, in function returning non-void
     return;
     ^~~~~~
  src/functools.c:38:1: note: declared here
   init_functools(void)
   ^~~~~~~~~~~~~~
  src/functools.c:49:2: warning: ‘return’ with no value, in function returning non-void
    return;
    ^~~~~~
  src/functools.c:38:1: note: declared here
   init_functools(void)
   ^~~~~~~~~~~~~~
  At top level:
  src/functools.c:28:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
   static const char rcsid[] = "@(#)$Dima: pylib/functools/src/functools.c,v 1.3 2005/08/22 07:39:33 dima Exp $";
                     ^~~~~
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ao3dude/project/include -I/usr/include/python3.6m -c src/compose.c -o build/temp.linux-x86_64-3.6/src/compose.o
  src/compose.c: In function ‘compose_dealloc’:
  src/compose.c:96:6: error: ‘struct compose’ has no member named ‘ob_type’; did you mean ‘ob_base’?
    co->ob_type->tp_free(co);
        ^~~~~~~
        ob_base
  src/compose.c: In function ‘compose_repr’:
  src/compose.c:137:6: warning: implicit declaration of function ‘PyString_FromFormat’; did you mean ‘PyBytes_FromFormat’? [-Wimplicit-function-declaration]
    s = PyString_FromFormat("<composition on %s at %p>",
        ^~~~~~~~~~~~~~~~~~~
        PyBytes_FromFormat
  src/compose.c:138:6: warning: implicit declaration of function ‘PyString_AsString’; did you mean ‘PyBytes_AsString’? [-Wimplicit-function-declaration]
        PyString_AsString(grepr), (void *)co);
        ^~~~~~~~~~~~~~~~~
        PyBytes_AsString
  src/compose.c:137:4: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    s = PyString_FromFormat("<composition on %s at %p>",
      ^
  src/compose.c: At top level:
  src/compose.c:143:36: warning: missing braces around initializer [-Wmissing-braces]
   static PyTypeObject compose_type = {
                                      ^
  src/compose.c:146:2: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
    "compose",   /* tp_name */
    ^~~~~~~~~
  src/compose.c:146:2: note: (near initialization for ‘compose_type.tp_basicsize’)
  src/compose.c:150:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    (destructor)compose_dealloc, /* tp_dealloc */
    ^
  src/compose.c:150:2: note: (near initialization for ‘compose_type.tp_print’)
  src/compose.c:155:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    (reprfunc)compose_repr,  /* tp_repr */
    ^
  src/compose.c:155:2: note: (near initialization for ‘compose_type.tp_as_number’)
  src/compose.c:160:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    (ternaryfunc)compose_call, /* tp_call */
    ^
  src/compose.c:160:2: note: (near initialization for ‘compose_type.tp_str’)
  In file included from /usr/include/python3.6m/pytime.h:6:0,
                   from /usr/include/python3.6m/Python.h:77,
                   from src/compose.c:31:
  /usr/include/python3.6m/object.h:659:29: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
   #define Py_TPFLAGS_DEFAULT  ( \
                               ^
  src/compose.c:165:2: note: in expansion of macro ‘Py_TPFLAGS_DEFAULT’
    Py_TPFLAGS_DEFAULT | Py_TPFLAGS_HAVE_GC |
    ^~~~~~~~~~~~~~~~~~
  /usr/include/python3.6m/object.h:659:29: note: (near initialization for ‘compose_type.tp_doc’)
   #define Py_TPFLAGS_DEFAULT  ( \
                               ^
  src/compose.c:165:2: note: in expansion of macro ‘Py_TPFLAGS_DEFAULT’
    Py_TPFLAGS_DEFAULT | Py_TPFLAGS_HAVE_GC |
    ^~~~~~~~~~~~~~~~~~
  src/compose.c:167:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    compose_doc,   /* tp_doc */
    ^~~~~~~~~~~
  src/compose.c:167:2: note: (near initialization for ‘compose_type.tp_traverse’)
  src/compose.c:168:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    (traverseproc)compose_traverse, /* tp_traverse */
    ^
  src/compose.c:168:2: note: (near initialization for ‘compose_type.tp_clear’)
  src/compose.c:179:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    PyMethod_New,   /* tp_descr_get */
    ^~~~~~~~~~~~
  src/compose.c:179:2: note: (near initialization for ‘compose_type.tp_descr_set’)
  src/compose.c:184:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    compose_new,   /* tp_new */
    ^~~~~~~~~~~
  src/compose.c:184:2: note: (near initialization for ‘compose_type.tp_free’)
  src/compose.c:185:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    PyObject_GC_Del,  /* tp_free */
    ^~~~~~~~~~~~~~~
  src/compose.c:185:2: note: (near initialization for ‘compose_type.tp_is_gc’)
  src/compose.c:143:36: warning: missing braces around initializer [-Wmissing-braces]
   static PyTypeObject compose_type = {
                                      ^
  src/compose.c:28:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
   static const char rcsid[] = "@(#)$Dima: pylib/functools/src/compose.c,v 1.3 2005/08/22 07:39:33 dima Exp $";
                     ^~~~~
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for functools
  Running setup.py clean for functools
Failed to build functools
DEPRECATION: Could not build wheels for functools which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: functools
    Running setup.py install for functools ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ao3dude/project/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-38iys3v6/functools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-38iys3v6/functools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-txqbxw7d/install-record.txt --single-version-externally-managed --compile --install-headers /home/ao3dude/project/include/site/python3.6/functools
         cwd: /tmp/pip-install-38iys3v6/functools/
    Complete output (115 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying functools.py -> build/lib.linux-x86_64-3.6
    running build_ext
    building '_functools' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ao3dude/project/include -I/usr/include/python3.6m -c src/functools.c -o build/temp.linux-x86_64-3.6/src/functools.o
    src/functools.c: In function ‘init_functools’:
    src/functools.c:43:6: warning: implicit declaration of function ‘Py_InitModule3’; did you mean ‘Py_Initialize’? [-Wimplicit-function-declaration]
      m = Py_InitModule3("_functools", NULL, functools_doc);
          ^~~~~~~~~~~~~~
          Py_Initialize
    src/functools.c:43:4: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
      m = Py_InitModule3("_functools", NULL, functools_doc);
        ^
    src/functools.c:45:3: warning: ‘return’ with no value, in function returning non-void
       return;
       ^~~~~~
    src/functools.c:38:1: note: declared here
     init_functools(void)
     ^~~~~~~~~~~~~~
    src/functools.c:49:2: warning: ‘return’ with no value, in function returning non-void
      return;
      ^~~~~~
    src/functools.c:38:1: note: declared here
     init_functools(void)
     ^~~~~~~~~~~~~~
    At top level:
    src/functools.c:28:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
     static const char rcsid[] = "@(#)$Dima: pylib/functools/src/functools.c,v 1.3 2005/08/22 07:39:33 dima Exp $";
                       ^~~~~
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ao3dude/project/include -I/usr/include/python3.6m -c src/compose.c -o build/temp.linux-x86_64-3.6/src/compose.o
    src/compose.c: In function ‘compose_dealloc’:
    src/compose.c:96:6: error: ‘struct compose’ has no member named ‘ob_type’; did you mean ‘ob_base’?
      co->ob_type->tp_free(co);
          ^~~~~~~
          ob_base
    src/compose.c: In function ‘compose_repr’:
    src/compose.c:137:6: warning: implicit declaration of function ‘PyString_FromFormat’; did you mean ‘PyBytes_FromFormat’? [-Wimplicit-function-declaration]
      s = PyString_FromFormat("<composition on %s at %p>",
          ^~~~~~~~~~~~~~~~~~~
          PyBytes_FromFormat
    src/compose.c:138:6: warning: implicit declaration of function ‘PyString_AsString’; did you mean ‘PyBytes_AsString’? [-Wimplicit-function-declaration]
          PyString_AsString(grepr), (void *)co);
          ^~~~~~~~~~~~~~~~~
          PyBytes_AsString
    src/compose.c:137:4: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
      s = PyString_FromFormat("<composition on %s at %p>",
        ^
    src/compose.c: At top level:
    src/compose.c:143:36: warning: missing braces around initializer [-Wmissing-braces]
     static PyTypeObject compose_type = {
                                        ^
    src/compose.c:146:2: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
      "compose",   /* tp_name */
      ^~~~~~~~~
    src/compose.c:146:2: note: (near initialization for ‘compose_type.tp_basicsize’)
    src/compose.c:150:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
      (destructor)compose_dealloc, /* tp_dealloc */
      ^
    src/compose.c:150:2: note: (near initialization for ‘compose_type.tp_print’)
    src/compose.c:155:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
      (reprfunc)compose_repr,  /* tp_repr */
      ^
    src/compose.c:155:2: note: (near initialization for ‘compose_type.tp_as_number’)
    src/compose.c:160:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
      (ternaryfunc)compose_call, /* tp_call */
      ^
    src/compose.c:160:2: note: (near initialization for ‘compose_type.tp_str’)
    In file included from /usr/include/python3.6m/pytime.h:6:0,
                     from /usr/include/python3.6m/Python.h:77,
                     from src/compose.c:31:
    /usr/include/python3.6m/object.h:659:29: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
     #define Py_TPFLAGS_DEFAULT  ( \
                                 ^
    src/compose.c:165:2: note: in expansion of macro ‘Py_TPFLAGS_DEFAULT’
      Py_TPFLAGS_DEFAULT | Py_TPFLAGS_HAVE_GC |
      ^~~~~~~~~~~~~~~~~~
    /usr/include/python3.6m/object.h:659:29: note: (near initialization for ‘compose_type.tp_doc’)
     #define Py_TPFLAGS_DEFAULT  ( \
                                 ^
    src/compose.c:165:2: note: in expansion of macro ‘Py_TPFLAGS_DEFAULT’
      Py_TPFLAGS_DEFAULT | Py_TPFLAGS_HAVE_GC |
      ^~~~~~~~~~~~~~~~~~
    src/compose.c:167:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
      compose_doc,   /* tp_doc */
      ^~~~~~~~~~~
    src/compose.c:167:2: note: (near initialization for ‘compose_type.tp_traverse’)
    src/compose.c:168:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
      (traverseproc)compose_traverse, /* tp_traverse */
      ^
    src/compose.c:168:2: note: (near initialization for ‘compose_type.tp_clear’)
    src/compose.c:179:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
      PyMethod_New,   /* tp_descr_get */
      ^~~~~~~~~~~~
    src/compose.c:179:2: note: (near initialization for ‘compose_type.tp_descr_set’)
    src/compose.c:184:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
      compose_new,   /* tp_new */
      ^~~~~~~~~~~
    src/compose.c:184:2: note: (near initialization for ‘compose_type.tp_free’)
    src/compose.c:185:2: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
      PyObject_GC_Del,  /* tp_free */
      ^~~~~~~~~~~~~~~
    src/compose.c:185:2: note: (near initialization for ‘compose_type.tp_is_gc’)
    src/compose.c:143:36: warning: missing braces around initializer [-Wmissing-braces]
     static PyTypeObject compose_type = {
                                        ^
    src/compose.c:28:19: warning: ‘rcsid’ defined but not used [-Wunused-const-variable=]
     static const char rcsid[] = "@(#)$Dima: pylib/functools/src/compose.c,v 1.3 2005/08/22 07:39:33 dima Exp $";
                       ^~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ao3dude/project/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-38iys3v6/functools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-38iys3v6/functools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-txqbxw7d/install-record.txt --single-version-externally-managed --compile --install-headers /home/ao3dude/project/include/site/python3.6/functools Check the logs for full command output.

**Comment by ArmindoFlores** [comment]
`cached_properties` is only available on python >=3.8. I wasn't aware of that fact when I published this package and that's why there's no error when you pip install it on an older python installation. Try installing python 3.8 an running it again.

**Comment by Wrench-wench** [comment]
For people following this. 
**Ubuntu 18.04 LTS** has a latest version of Python is 3.6.9
You will need to follow this guide to get it working with Python3.8 (Change all instances of Pyton3.7 to Python3.8 in the steps, I have tested it working) https://tech.serhatteker.com/post/2019-09/upgrade-python37-on-ubuntu18/

**Ubuntu 19.04** comes with Python3.7 
Follow steps for Ubuntu 18.04 LTS

**Ubuntu 20.04** comes with Python 3.8.2
So you will be ok.

**Comment by searchtools-avi** [comment]
I get that error on Mac OS High Sierra, Anaconda, both Spyder and Jupyter.  I got it on Python 3.7 and updated to 3.8 (and restarted) -- it's still happening.  Here's what I see, please tell me if there is anything else 

`  File "<ipython-input-2-dfc1763c82ec>", line 1, in <module>
    import AO3

  File "/opt/anaconda3/lib/python3.7/site-packages/AO3/__init__.py", line 2, in <module>
    from .comments import Comment

  File "/opt/anaconda3/lib/python3.7/site-packages/AO3/comments.py", line 5, in <module>
    from .users import User

  File "/opt/anaconda3/lib/python3.7/site-packages/AO3/users.py", line 2, in <module>
    from functools import cached_property

ImportError: cannot import name 'cached_property' from 'functools' (/opt/anaconda3/lib/python3.7/functools.py)
`

**Comment by Wrench-wench** [comment]
From your error message it's utilising Python3.7 to run. That's more an OS issue than a AO3_API issue.

You may need to update your environment variables for Python to ensure it's using Python 3.8.
What output do you get if you run ```python --version```?

**Comment by searchtools-avi** [comment]
You're right, looks like Anaconda reverted me to 3.7 when I ran it.

I'm looking at how to upgrade Anaconda, but in the meantime, is there a way around the error?  I'm not doing enough to need caching right now.  Pip installs AO3-api 2.02, which might not have your fix in it, and I'm not clear on how to get around it.  Any hints gratefully accepted.

BTW, I am teaching myself python and BeautifulSoup on AO3, then I found your old API and it was very helpful but I needed a session object for getting works and I found this nice new very and am a happy camper.  Thank you!

**Comment by ArmindoFlores** [comment]
You can try to install [this](https://pypi.org/project/cached-property/) python package using `pip install cached-property` and replacing all instances of `from functools import cached_property` with `from cached_property import cached_property`. However, I don't recommend this and I think you'd be better off just upgrading to python 3.8

**Comment by ArmindoFlores** [comment]
Also as a side note, I'm working on removing the use of `cached_property` altogether, because using it forces me to store the soup object instead of just calculating everything at load time, and that then makes a pickled Work, Series or Session object very big and much more complex than it needed to be.
